codecov:
  bot: codecov.io
  require_ci_to_pass: yes

coverage:
  round: nearest
  range: 75..100
  status:
    project:
      default:
        target: 75%
        threshold: 10%
        if_not_found: failure
        if_ci_failed: error
